spring.application.name=agendasena

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/agendasena_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Propiedades de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Permitir la inicialización automática con archivos SQL
spring.jpa.defer-datasource-initialization=true